language: ruby
rvm:
- 2.0.0
- 1.9.3
after_script: ./deploy.sh
secure: "dmUR47L+7wQXoVMkVxfAAXkfbY4Ukq1915laUvyfg7ac4XTnEHECu1qp9p8sC552GB95zX77Rbb3aSTHO9o2uXT074PWd0GUXxXuqAib3NKyCmYPAW+2R5F2d8FjTkFCh6Nmb2KQI0OUVHbYQMwqJ6ujM4BHN35/6ewhr7FOuUQ="
dd:
  secure: Hu0notVRIo7iEUwJUYPid3qpfcQw7gksjG0RKJD4885gSSLdoRZ0Zear2ZZp+ttFH3+iB7LZiRtNT74lztnoIFO2tnjzGdHfqo3PgqtMeRLAAtQOSGTrKzaiAlx5iOfjXaloNGZLyCFBr4BnwIX7XnicDfiMwT2uxpHkFEfDE5Y=
