language: ruby

rvm:
- 2.0.0

after_script: ./deploy.sh

services:
  - mongodb

env:
  global:
  - secure: SkOYUTwua5VDLAumMcVaXlgqBF9ozG1kbLqjLbm/ytcD/G8a3Uiji4rfAWIKeF9L4OJR+Nl7kX//rwPxeSwIcg9QI4druHylm66RP0xEDPEOruLSclAG+PVE6Ymf0Ls0DIrivvTD2od5llnGxl+qKqnlOz67+RpZCF3kM8gWwq0=
  - secure: PmZ4IpST6g/dca8Iid9LT77RWHIL6+n5DyZdLhaAJMEKIYhSgAlXk6QIrHFfqoL3u59LfAIZHLQ4DU3fbUYvWnvihZ8SHszLFSOQIxnfWJ6fOtbcL3PLyePV/9OcInqQ2eeXKu1tfdhheeD5AfGhrpldzplTbCVDRaZAFlgEedA=
  - secure: BqSGXYhgG1dyuRXteBSWWJHdc3K17zEAFfjNG0LqqkJttK6dZmmKwWU7Y2uMKFeIkccnWryfhIeIs1JEtWX4UsmwoNoxQi5KpNHWDBFFYCjTZ11Jvs0f8ydPS+QCpKlhm7U3y3YrI02eO7HQbPMzKOWx2VwT8zO5NrpMuicOkvc=
  - secure: ZckzagvSZqXF1nhB57lVgUjxAHk+i5zhi2j+Mkq+4ozpIgogptC/phryLWvpGicugT/TE2iPGRQelM7+ymJDo27GC3yhzleG+1BWuVB9b5PE/SaqjV4wVHpXX7DgOl7tOoq7cdvckIfF3cavLk5WCTJNeo4F8XDMCCQzWBMmlLg=
  - secure: cKVo7+/CalZmiGURF90p92HXmgdN1XqsvpZ6ZVSG1lFirjZF0I8rwuDSv8jMvicEaE++GqV6V2ahP7UURhAQwphgtqmGLi9VksCLAwL07/ll7orZFeI9UjKaQhK0ZoUmJ9M5R85+dPfm41psUSao8PsJQ1XiGhbtjTSRRgJoRhU=
  - secure: XEupbuQXYqtO1WxZhHu2K1kloxSPfRg+xTdV7SEKipNrwl2jvUMm3TiKRxaDopaI0zQKSOhV14AVPLFEAASdVtlWSMP1yk2ijPb+dYm2I0AQjxLUWO97HZy4FXfpBs1eKBJOBV6itbQzZmnVwdlrHdTxiC8tr1NwNYc5d3piSp0=
  - secure: TlWMSFw7Xim0lujLK1FX70Tlsy5+rFA4Vu9HQxkIGEJqwdKBlhIvDMHcP7Z6lu0HNucnUZwXZTmOGfNTeUxNO0WNTf870P2L7BDONrKD4ug0V++wqKvwbyCLYtBeYnZpBxi9PghV5TAD5YB7It4/Ea4phTZ9X5W8FWZ59LmFghw=
  - secure: AaLe51/sCcKpKxd/9M94/olrAW6/CQrFeLhTIb9MFGg2T5v2MNXDUwLT0mBBUKe9YO8cSWJ2N/bF+bAEzMXlUMQ7viz/5B9sCUhx3nl+HYNZN38G9OdQpcjgCi5TXF4sX6QFKDlQF4+TXUUAwJ2w9chzdCNekstbPyFIwHrjN8U=
  - secure: QRKe/U4xyR9TgNZvvrQawE3M/rEe508v6MwjGqlNcQChahlVwTIM0mkx0s4EZxqwJnAplK/wcaMy5ppN8n2Q9eqgkcQv0WDvY1tkrH4mEkExhyqbdpMZXjcXLTsQJZo6LQp6xFLKBDsWiDUAYTnSGOTbx09kG2qkidK5UXkleXs=
  - secure: IcYAcSn+AwA9DK64/odwcM13I5EXsaGzaVvBPzFzhqn85comPeOymHEgirxptHRuDGdtYJX4Ri2d+qYGYoKQ2HXj0INArasTGUurDSA1qpaNx1KXJX2mK5NX7YwDogZN+ITDL/nLrRG+t9gfcwNAVPbkHVbJgzInJ5aiO5Q1YW0=
  - secure: F4Cjllh29ik3HTF/4n0milxSmUPDw4zknsaD2U/udxFYkNTrkd/eLxtkc9ZTkpVnECFq38EAaR1QYVPybgNZiK0GYwT/Pt5mm0MZwhkKSzX7NmHG/OEKZnILg0XAT/1NHR5NMvK6O+CFsETegP7Uf8wtlk1I7Yky5IbEcIO1KsE=
  - secure: MS6D4+Yww3rcBFL9BbFQTem+/N93DuBMM7GLvvnIfF62MepHlaC9ZsVaq8H6rAYi9NfaLoiWoG8PsXYe+STmWBfNu6ieZE4rms50IhoTnKnD6FswG7t5A9aQ9Ti9a/rsABNdEWBofhSDLA+FkvtFknRitynY+botSWD7sEeQJrw=
  - secure: EccbOPaNXOM6fDAmVoS9aHyNM4Dxklq4ViGjeWR/8vaf5TIHg4fWI1hYtAgtwNf9K1FqCHQ6flqt4mTrCYXDPBGyLmCXpQ6VhhXfT1km0gkf4/SuSk30TqqDKfy2k3RAG84wbEJhTkZTtJZ9wE6s487RCTWVIUvZjt2BgRk1d/s=
  - secure: Vx17rr3rARgnx2De+yWN/Wl4TYSw6aYtLrbq5xZz01pacAfX1h7huzanOoQEjDR/hZGX/Cv01KlQ8E+NCeSsI8ljmvPR5hHLqGqPTyolgZdfLOXtO1kZe9PnWnVSy5FOA5ryTs6FE9Ppg+uyTxW//cqdrDjs/L6QPpEs7ccuc3M=
  - secure: G+P+SpdUI/fWiQb2LB2eWwxJA6dgacBIsfASUTEV2ZUFTXCr7ARElkfwvcAV1vnvuRw/xVAFdtV4Oz4B0GJUVPlasR2E3j+eCGXJ06lbDo7xU+FFSG6fs3BKJbhNNEnZ2dC7TQFMZzW0Xm/8iPm0d08OYaDUHcWPtH/Q8z39dB4=
  - secure: IbAMzTYH7yoPOE/muz0PT8B/RyuUbUEvU1P5OCoCXEtUyAvAp32WhOqOWm9WcmyiHGTBByFj/YitPCdAA6iU6Mw/E9hY74GEHH/PduxHIyDxurIz2NsDaXGxjyCMItlMBnWr41IUXxbGOA5SRVZgMPmtdk7E96DRh7nlEnWFtqY=
  - secure: fRMDCTBxbu4tXvOXXtoMfNoliEZBDbKzVAAqTldVKtz1mAf95MGdrqwzx9C4YQiSqEqfDJuNGNzdepaY+4Ko6L1dwXLRiu++PaCIr3vHDU8lL2m4TiFjIWuTGMPnC19tXLlicaFvkKMoCdJ/XulKr/kXICiYC8M1weK7XqyxMBc=
  - secure: X6sIufI826Vr7El5rgLXhsPOwgBxV7W0UkJu4BKHMj8Jy9/WbIKPzzrzUEZUln5Vd94v3tQg+LohkJnBEdaRl8m8sZhliVLqVO3X7c9r0JvAhBaoH+UQ9nwk7N03HMzGm/JmCRSuCM0n8QGBNfaTD+JPjHGAeiIGF/gyVS9WbY4=
  - secure: fF+xMlyCAXQ2qBOk4UVt8CG2HMfHZAP2JQS4BrfAB5m6dSuUWJNC4Cv03SwaYXlacpf3BHbPlj2yoE+r7EfxFsSgZu6t5phhqmKJNVUDKiZzLCha/nlfb1WAqTn3lWnHdTV8EMiAGDcQGiBckAmEm2La4cnZl4goUlGlD75INNA=
  - secure: Wytd5jIhJSi1ueAEPXSqezVChJ3fqIT0lCfF3cKBRr/tCPDfjgtHXtiooz9JS0scAPAK8StgzYnCjXA5OA1KU713SflBExfSX08DXEDGvRb2Ogs4SFugI7vKt7a0BqN5r/m+PIrpvZQxrP7b/rtFDwM5oLyRaV6+3hv3wAs+Ye4=
  - secure: PlBrMAra4aY8U5FmeN8NeHYVodjv7hALykk/YC8lPZ5BhYQ9SUvowh2k/wdrY/Suk6baUmOdPLjcnvsqd6YEWQUGzJqtUis7ItZ8msUTqbnqUKyS2o95bkursfiGVQTVclvHKkarx2YxcKIk/4+WFZ47Q6wDxjRlwo8rZgfuwys=
