language: ruby
rvm:
- 2.0.0
- 1.9.3
after_script: ./deploy.sh
dd:
  secure: Hu0notVRIo7iEUwJUYPid3qpfcQw7gksjG0RKJD4885gSSLdoRZ0Zear2ZZp+ttFH3+iB7LZiRtNT74lztnoIFO2tnjzGdHfqo3PgqtMeRLAAtQOSGTrKzaiAlx5iOfjXaloNGZLyCFBr4BnwIX7XnicDfiMwT2uxpHkFEfDE5Y=
