pm25_query_url: 'http://www.pm25.in/api/querys/pm2_5.json'
token: 'RQCxTwiUMjhhcL4k3S3a'
app_url: 'http://54.199.131.70'
image_src:
  - 'http://www.baikce.cn/upload/apk/2013/11/19/528b4b6adb36f.jpg'
  - 'http://image.zcool.com.cn/2013/06/38/61/m_1361793427683.jpg'
  - 'http://img.jrjimg.cn/2013/12/20131226151316226.png'
  - 'http://www.99earth.org/wp/wp-content/uploads/2013/05/webpage_PSD0422.jpg'
  - 'http://www.hsdcw.com/photo/upload/2013-12-28/20131228955564841.jpg'
  - 'http://www.tuvie.com/wp-content/uploads/fire-relief-respirator1.jpg'